'use client';

import { useEffect, useRef, useState } from 'react';
import './ksj-chat.css';

/* The chat widget itself lives in lib/ksj-chat.js and is shared with kangseongjun.com,
 * which is a hand-written HTML page with no build step. That is why it is plain JS on
 * window rather than a React component: one copy has to run on both sites.
 *
 * It is imported inside an effect because the widget attaches to `window` at module
 * scope, and this site is a static export, so a top-level import would run during
 * prerender in Node and throw. */

interface ChatOptions {
  apiBase: string;
  title?: string;
  intro?: string;
  placeholder?: string;
  disclaimer?: string;
  hint?: string;
  suggestions?: string[];
}

declare global {
  interface Window {
    KSJChat?: { mount: (el: HTMLElement, opts: ChatOptions) => unknown };
  }
}

const API_BASE = process.env.NEXT_PUBLIC_CHAT_API ?? '';

/* Copy tracks content/site.yaml in the KSJ-portfolio-fable repo, which is where the
 * chatbot and its corpus live. The heading speaks in his voice because it is his site;
 * the questions speak in a visitor's, because that is who types them and the bot answers
 * about him in the third person.
 *
 * These four are aimed at the reader who decides whether to read the CV: a computational
 * PI. Method building, inference under ambiguity, bench-to-code range, and how he checks
 * a model. Each was run against the corpus first, because site.yaml is right that a
 * suggestion the corpus cannot answer makes a refusal the first thing a visitor sees.
 * Two obvious candidates were cut for exactly that: "the largest dataset he has analysed"
 * only gets a hedge, and "what is he looking for in a postdoc" is a flat refusal while
 * profile.yaml has no headline or summary. */
const SUGGESTIONS = [
  'What has he built from scratch rather than run as an off-the-shelf tool?',
  'How does he infer cell identity when the data is incomplete or truncated?',
  'What machine learning has he validated, and how?',
  'How does his wet-lab experience change the way he analyses data?',
];

export default function ResearchChat() {
  const ref = useRef<HTMLDivElement>(null);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    if (!API_BASE) return;
    let cancelled = false;

    import('@/lib/ksj-chat')
      .then(() => {
        if (cancelled || !ref.current || !window.KSJChat) return;
        window.KSJChat.mount(ref.current, {
          apiBase: API_BASE,
          title: 'Ask about my research',
          intro:
            'This answers from my publications, research notes, and CV, and cites what it used. ' +
            'If the answer is not in those files, it will say so rather than guess.',
          placeholder: 'Ask about a paper, a method, or a collaboration',
          disclaimer:
            'Answers are generated by a language model from the files in this repository. ' +
            'Check anything that matters against the cited source.',
          suggestions: SUGGESTIONS,
        });
      })
      .catch(() => {
        if (!cancelled) setFailed(true);
      });

    return () => {
      cancelled = true;
    };
  }, []);

  // With no API host configured there is no chatbot, and an input box that cannot answer
  // is worse than no input box. Same when the bundle fails to load.
  if (!API_BASE || failed) return null;

  return <div ref={ref} className="ksj-chat-hero" />;
}
